# name: CI/CD
# on:
#     pull_request:
#         types:
#             - closed
#         branches:
# jobs:
#     bump:
#         runs-on: ubuntu-22.04
#         permissions:
#             contents: write
#         outputs:
#         steps:
#             - uses: actions/checkout@v4
#               with:
#                   fetch-depth: '0'
#             - name: Bump version and push tag
#               id: bump_version
#               uses: anothrNick/github-tag-action@v1
#               env:
#                   WITH_V: true
#                   PRERELEASE: false
#     cd:
#         needs: bump
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout
#               uses: actions/checkout@v3
#             - name: Login to docker
#               uses: docker/login-action@v3
#               with:
#             - name: Debug current directory
#               run: |
#                   echo "Current directory:"
#                   pwd
#                   echo "Contents:"
#                   ls -la
#             - name: Build and push
#               run: |
#                   echo "Repository name: $REPO_NAME"
#                   docker build \
#                   docker push 